#!/usr/bin/env python3
"""Weekly upstream link-health check over state/upstream-sources.tsv
(generated by scripts/export-upstream-sources.sh from the mounted caskets).

A row is judged the way the fetch pipelines actually behave — a fallback
chain of codeload archive URLs — so "bad" means "the pipeline could not
re-fetch this source today":
    pin rows:  <ref>  ->  v<version>  ->  <version>
    tag rows:  v<version>  ->  <version>
    head rows: HEAD (repo default branch)
Repo-level: one GitHub API call each (deletion / rename / private).

Known, accepted rot lives in state/upstream-links-baseline.txt (one
"repo<TAB>ref-or-version" per line); only NEW rot fails the job. Refresh
the baseline deliberately with --write-baseline after reviewing a run.

Local:  python3 scripts/check-upstream-links.py [--limit N] [--jobs 8]
        [--write-baseline]
Env: GITHUB_TOKEN (recommended: 5000 req/h API quota).
Exit: 0 ok / 1 NEW rot found / 2 manifest missing.
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import json
import os
import sys
import urllib.error
import urllib.request

STATE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "state")
MANIFEST = os.path.join(STATE, "upstream-sources.tsv")
BASELINE = os.path.join(STATE, "upstream-links-baseline.txt")
UA = {"User-Agent": "casket-link-check"}


def http_status(url: str, method: str = "GET", token: str | None = None,
                timeout: int = 20) -> int:
    hdrs = dict(UA)
    if token and "api.github.com" in url:
        hdrs["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=hdrs, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status
    except urllib.error.HTTPError as e:
        return e.code
    except Exception:
        return 0


def check_repo(repo_url: str, token: str | None) -> tuple[str, str]:
    """-> (state, detail). state: ok | moved | gone | error"""
    org_repo = repo_url.split("github.com/", 1)[1]
    req = urllib.request.Request(
        f"https://api.github.com/repos/{org_repo}",
        headers={**UA, **({"Authorization": f"Bearer {token}"} if token else {})})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            full = json.load(r).get("full_name", "")
        if full and full.lower() != org_repo.lower():
            return "moved", full
        return "ok", ""
    except urllib.error.HTTPError as e:
        if e.code in (404, 451):
            return "gone", f"HTTP {e.code}"
        return "error", f"HTTP {e.code}"
    except Exception as e:
        return "error", str(e)[:60]


def candidates(ref: str, version: str, kind: str) -> list[str]:
    c: list[str] = []
    if kind == "head":
        return ["HEAD"]
    if ref:
        c.append(ref)
    if version:
        if f"v{version}" != ref:
            c.append(f"v{version}")
        if version != ref:
            c.append(version)
    return c


def check_row(row: tuple[str, str, str, str, str]) -> tuple[str, str]:
    """-> (state, detail). ok if ANY candidate archive URL answers 200."""
    repo, ref, version, kind, _seen = row
    org_repo = repo.split("github.com/", 1)[1]
    last = "no candidates"
    for cand in candidates(ref, version, kind):
        st = http_status(f"https://codeload.github.com/{org_repo}/tar.gz/{cand}",
                         method="HEAD")
        if st == 200:
            return "ok", cand
        last = f"{cand}:HTTP {st}"
    return "bad", last


def row_key(row: tuple[str, str, str, str, str]) -> str:
    repo, ref, version, kind, _ = row
    return f"{repo}\t{ref or version or kind}"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--write-baseline", action="store_true",
                    help="accept current rot as the new baseline")
    args = ap.parse_args()
    token = os.environ.get("GITHUB_TOKEN")

    if not os.path.isfile(MANIFEST):
        print(f"manifest not found: {MANIFEST}")
        return 2
    rows: list[tuple[str, str, str, str, str]] = []
    for line in open(MANIFEST):
        if line.startswith("#") or not line.strip():
            continue
        c = line.rstrip("\n").split("\t")
        if len(c) >= 5:
            rows.append((c[0], c[1], c[2], c[3], c[4]))
    if args.limit:
        rows = rows[: args.limit]
    baseline: set[str] = set()
    if os.path.isfile(BASELINE):
        baseline = {l.rstrip("\n") for l in open(BASELINE) if l.strip()}

    repos = sorted({r[0] for r in rows})
    print(f"checking {len(repos)} repos / {len(rows)} rows "
          f"(baseline: {len(baseline)} accepted)")

    with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        repo_state = dict(zip(repos, ex.map(lambda r: check_repo(r, token), repos)))
    gone_repos = {r: d for r, (s, d) in repo_state.items() if s == "gone"}
    moved_repos = {r: d for r, (s, d) in repo_state.items() if s == "moved"}

    live_rows = [r for r in rows if repo_state.get(r[0], ("ok", ""))[0] != "gone"]
    bad: list[tuple[tuple[str, str, str, str, str], str]] = []
    with cf.ThreadPoolExecutor(max_workers=args.jobs) as ex:
        for row, (st, detail) in zip(live_rows, ex.map(check_row, live_rows)):
            if st != "ok":
                bad.append((row, detail))

    bad_keys = {row_key(r) for r, _ in bad} \
             | {f"{r}\t(repo)" for r in gone_repos}
    new = sorted(bad_keys - baseline)
    fixed = sorted(baseline - bad_keys)

    print("\n=== summary ===")
    print(f"repos: {len(repos)} checked, {len(gone_repos)} gone, "
          f"{len(moved_repos)} renamed (redirects still work)")
    print(f"rows:  {len(live_rows) - len(bad)} re-fetchable, {len(bad)} not")
    print(f"vs baseline: {len(new)} NEW, {len(fixed)} recovered")
    for k in new[:50]:
        print(f"NEW ROT: {k}")
    if len(new) > 50:
        print(f"  ... and {len(new) - 50} more")
    for r, tgt in sorted(moved_repos.items()):
        print(f"RENAMED: {r} -> {tgt}")

    if args.write_baseline:
        with open(BASELINE, "w") as f:
            f.writelines(k + "\n" for k in sorted(bad_keys))
        print(f"baseline written: {len(bad_keys)} entries -> {BASELINE}")
        return 0
    return 1 if new else 0


if __name__ == "__main__":
    sys.exit(main())
