#!/usr/bin/env bash
# Incrementally refresh the ocp-srpms casket after collecting newly-available
# .src.rpm (e.g. EUS z-stream micros that were missing at first build), WITHOUT
# re-fetching the whole set or copying the ~70G extracted pool.
#
# Method (same overlayfs trick as repackage-add-index.sh): extract only the NEW
# SRPMs into an overlay upper layer over the read-only mount, then regenerate
# by-ocp/ + meta/bin-to-src.tsv (via the fixed phase-a-rpm-by-ocp.sh) and merge
# meta/MANIFEST.json through the merged view. mksquashfs the merged tree. The
# bulk source bytes are reused from the mount; only new sources + the regenerated
# index land in the upper layer.
#
# Usage: repackage-srpms-refresh.sh -m <mount> -s <new-srpm-dir> -r <rpmdb-dir> -o <out.sqfs.xz>
#   -m  read-only casket mount (e.g. /srv/sources-ocp-srpms)
#   -s  dir of newly-collected *.src.rpm (already-present NEVRs are skipped)
#   -r  per-OCP rpmdb tsv dir (defaults to <mount>/meta/rpmdb)
#   -o  output .sqfs.xz path
# Requires: sudo (overlay + loop already mounted), mksquashfs, rpm, python3.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MOUNT=""; NEWSRPM=""; RPMDB=""; OUT=""; EXTRA_META=(); UPPER_PERSIST=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        -m) MOUNT="$2"; shift 2 ;;
        -s) NEWSRPM="$2"; shift 2 ;;
        -r) RPMDB="$2"; shift 2 ;;
        -o) OUT="$2"; shift 2 ;;
        -M) EXTRA_META+=("$2"); shift 2 ;;   # extra file(s) to place under meta/
        -u) UPPER_PERSIST="$2"; shift 2 ;;  # persistent upper dir: reused across runs, never deleted
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done
[[ -d "$MOUNT" && -d "$NEWSRPM" && -n "$OUT" ]] || {
    echo "usage: $0 -m <mount> -s <new-srpm-dir> [-r <rpmdb>] -o <out.sqfs.xz>" >&2; exit 1; }
RPMDB="${RPMDB:-$MOUNT/meta/rpmdb}"
[[ -d "$RPMDB" ]] || { echo "rpmdb dir not found: $RPMDB" >&2; exit 1; }

# Work dirs MUST be disk-backed: /tmp is tmpfs (~RAM/2) and the upper layer
# holds every newly-extracted SRPM tree — the 2026-07-19 container-RPM batch
# (~2,200 SRPMs, >100G) filled tmpfs instantly. upperdir/workdir must share
# one filesystem; root has the space.
TMP_BASE="${CASKET_WORK:-$HOME/casket-work}/.refresh-tmp"
mkdir -p "$TMP_BASE"
if [[ -n "$UPPER_PERSIST" ]]; then mkdir -p "$UPPER_PERSIST"; UPPER="$UPPER_PERSIST"; else UPPER=$(mktemp -d -p "$TMP_BASE"); fi
WORKD=$(mktemp -d -p "$TMP_BASE"); MERGED=$(mktemp -d -p "$TMP_BASE")
cleanup() {
    mountpoint -q "$MERGED" && sudo umount "$MERGED" || true
    # by-ocp regen runs under sudo, so upper/workd hold root-owned files.
    [[ -z "$UPPER_PERSIST" ]] && sudo rm -rf "$UPPER"
    sudo rm -rf "$WORKD"; rmdir "$MERGED" 2>/dev/null || true
}
trap cleanup EXIT

# 1. Extract only NEW SRPMs (skip NEVRs already in the mounted pool).
mkdir -p "$UPPER/srpms" "$UPPER/meta"
new=0; skip=0
for f in "$NEWSRPM"/*.src.rpm; do
    nevr=$(rpm -qp --qf '%{NAME}-%{VERSION}-%{RELEASE}' "$f" 2>/dev/null) || continue
    if [[ -d "$MOUNT/srpms/$nevr" ]]; then skip=$((skip+1)); continue; fi
    "$SCRIPT_DIR/phase-a-rpm-extract-one.sh" "$f" "$UPPER/srpms"
    new=$((new+1))
done
echo "[refresh] extracted $new new SRPMs into upper ($skip already in pool)"
[[ "$new" -gt 0 ]] || echo "[refresh] WARNING: no new SRPMs — index will only reflect resolver changes"

sudo chmod -R a+rX "$UPPER"; sudo chmod 755 "$UPPER"

# 2. Overlay the upper (new sources) over the read-only mount.
sudo mount -t overlay overlay \
    -o lowerdir="$MOUNT",upperdir="$UPPER",workdir="$WORKD" "$MERGED"

# 3. If the caller supplied an rpmdb set different from the casket's own
#    (e.g. new OCP patches replacing old ones), replace meta/rpmdb/ in the
#    merged view so the shipped tsvs always match the regenerated by-ocp/.
if [[ "$(readlink -f "$RPMDB")" != "$(readlink -f "$MOUNT/meta/rpmdb")" ]]; then
    sudo rm -rf "$MERGED/meta/rpmdb"
    sudo mkdir -p "$MERGED/meta/rpmdb"
    sudo cp "$RPMDB"/*.tsv "$MERGED/meta/rpmdb/"
    echo "[refresh] meta/rpmdb replaced with $(ls "$RPMDB"/*.tsv | wc -l) tsvs from $RPMDB"
fi

# 3b. Regenerate by-ocp/ + meta/bin-to-src.tsv through the merged view. The script
#    rm -rf's by-ocp (overlay whiteout -> opaque) and rewrites it + bin-to-src.tsv,
#    all of which land in the upper layer. Reads the full merged pool so the newly
#    added sources now satisfy exact (V,R) matches. Runs under sudo: rm -rf of the
#    lower-backed by-ocp/ creates overlay whiteouts (mknod), which needs root.
sudo "$SCRIPT_DIR/phase-a-rpm-by-ocp.sh" -s "$MERGED" -r "$RPMDB"

# 4. Merge MANIFEST.json: keep the existing srpms[] provenance list, append the
#    new sources, bump totals.srpms + regenerate timestamps. Under sudo because
#    the sudo by-ocp step already copied meta/ up into the (root-owned) upper.
sudo python3 - "$MOUNT/meta/MANIFEST.json" "$NEWSRPM" "$MERGED/meta/MANIFEST.json" <<'PY'
import sys, json, os, hashlib, subprocess, glob, datetime
old_path, newdir, out_path = sys.argv[1:4]
m=json.load(open(old_path))
have={s.get("nevr") for s in m["srpms"]}
added=0
for f in sorted(glob.glob(os.path.join(newdir,"*.src.rpm"))):
    nevr=subprocess.check_output(["rpm","-qp","--qf","%{NAME}-%{VERSION}-%{RELEASE}",f],
                                 stderr=subprocess.DEVNULL).decode().strip()
    if not nevr or nevr in have: continue
    h=hashlib.sha256(open(f,"rb").read()).hexdigest()
    m["srpms"].append({"file":os.path.basename(f),"sha256":h,
                       "size":os.path.getsize(f),"nevr":nevr})
    have.add(nevr); added+=1
m["srpms"].sort(key=lambda s:s.get("nevr",""))
m["totals"]["srpms"]=len(m["srpms"])
now=datetime.datetime.now(datetime.timezone.utc)
m["generated_at"]=now.strftime("%Y-%m-%dT%H:%M:%SZ")
m["date"]=now.strftime("%Y%m%d")
json.dump(m,open(out_path,"w"),indent=2)
print(f"[refresh] MANIFEST: +{added} srpms (total {m['totals']['srpms']})")
PY

# 4b. Extra meta files (e.g. image-rpms.tsv: image digest -> SRPM map for the
#     container-RPM layer; image-rpms-unfetchable.txt: the named gap list).
for xm in "${EXTRA_META[@]}"; do
    [[ -f "$xm" ]] || { echo "[refresh] WARNING: extra meta missing: $xm"; continue; }
    sudo cp "$xm" "$MERGED/meta/$(basename "$xm")"
    echo "[refresh] meta/$(basename "$xm") added"
done

# 5. mksquashfs — same flags as phase-a-rpm-package.sh. Under sudo so it can read
#    the root-owned by-ocp/ + meta/ the regen produced in the upper layer; then
#    hand the artifact back to the invoking user for the usual swap flow.
rm -f "$OUT"; mkdir -p "$(dirname "$OUT")"
echo "[refresh] mksquashfs -> $OUT"
sudo mksquashfs "$MERGED" "$OUT" \
    -comp xz -Xbcj x86 \
    -no-progress -all-root -no-xattrs -noappend
sudo chown "$(id -u):$(id -g)" "$OUT"
echo "[refresh] done: $OUT ($(du -h "$OUT" | cut -f1))"
